# Generated by Django 6.0.6 on 2026-07-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='solde_epargne',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('retrait', 'Retrait'), ('facture', 'Paiement de facture'), ('marchand', 'Paiement marchand QR'), ('epargne_depot', 'Dépôt épargne'), ('epargne_retrait', 'Retrait épargne'), ('credit', 'Micro-crédit accordé')], max_length=20),
        ),
    ]
