# Generated by Django 6.0.6 on 2026-07-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('retrait', 'Retrait'), ('facture', 'Paiement de facture'), ('marchand', 'Paiement marchand QR'), ('epargne_depot', 'Dépôt épargne'), ('epargne_retrait', 'Retrait épargne'), ('credit', 'Micro-crédit accordé'), ('depot_banque', 'Dépôt bancaire'), ('retrait_banque', 'Virement vers banque')], max_length=20),
        ),
    ]
